---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      changed_when: false

    - name: Create Ansible temporary directory
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: '0700'

    - name: Gather facts
      setup:

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - systemd
          - systemd-sysv
          - python3-pip
          - gnupg
          - curl
          - dbus
        state: present

    - name: Create systemd directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /run/systemd
        - /run/systemd/system
        - /run/systemd/systemd

    - name: Install Ansible MongoDB collection
      command: ansible-galaxy collection install community.mongodb
      changed_when: true

    - name: Start systemd
      command: /lib/systemd/systemd --system &
      async: 0
      poll: 0
      changed_when: false
      failed_when: false

    - name: Wait for systemd
      wait_for:
        path: /run/systemd/system
        state: present
        timeout: 30

    - name: Check systemd status
      command: systemctl status
      register: systemd_status
      changed_when: false
      failed_when: false

    - name: Show systemd status
      debug:
        var: systemd_status.stdout_lines

    - name: Check if dbus is running
      command: systemctl status dbus
      register: dbus_status
      changed_when: false
      failed_when: false

    - name: Show dbus status
      debug:
        var: dbus_status.stdout_lines 