---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check MongoDB service status
      systemd:
        name: mongodb
        state: started
        enabled: true

    - name: Check MongoDB port
      wait_for:
        port: 27017
        timeout: 30

    - name: Test MongoDB connection
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_port: 27017
        login_user: admin
        login_password: "{{ mongo_admin_pass }}"
        database: admin
        command: 'db.runCommand({ping: 1})'
      register: mongo_test

    - name: Verify MongoDB version
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_port: 27017
        login_user: admin
        login_password: "{{ mongo_admin_pass }}"
        database: admin
        command: 'db.version()'
      register: mongo_version_check

    - name: Assert MongoDB version matches expected version
      assert:
        that:
          - mongo_version_check.stdout is match("^" + mongo_version)
        msg: "MongoDB version {{ mongo_version_check.stdout }} does not match expected version {{ mongo_version }}"

    - name: Check MongoDB data directory
      file:
        path: "{{ mongo_storage.dbPath }}"
        state: directory
        owner: mongodb
        group: mongodb
        mode: '0755'

    - name: Check MongoDB log file
      file:
        path: "{{ mongo_systemlog.path }}"
        state: file
        owner: mongodb
        group: mongodb
        mode: '0644' 